Ревью
mikhail-os-git/ps-advanced-js pull request #1
Opened 2024-12-03 20:57 UTC by mikhail-os-git

2024-12-06 07:26 UTC, GitEsense approved these changes
Отсутствует в ПР задание `Set`, но оно существует в main ветке - это "ошибка", 4-timer не проверял, т.к. относится к следующему ДЗ (хорошо бы разделять ПРы между ДЗ)

Пример реализации `Set`
```js
const uniquePerson = [...new Set(arr.map(item => arr.find(el => item.id === el.id)))]
```
Всё отлично, но так будет корректнее, ведь мы уже не будем трогать Set, ибо он свою задачу делает "в конце"

т.е. берём
1. const array = arr.map => id => arr.find(a => a.id === id)
2. new Set(array)

Т.е. если разобрать "пример" и построчно, то
дано (где value для наглядности):
```js
const arr = [
    { id: 1, name: 'Вася', value: 1 },
    { id: 2, name: 'Петя', value: 2 },
    { id: 1, name: 'Вася', value: 3 },
    { id: 1, name: 'Вася', value: 4 },
    { id: 2, name: 'Петя', value: 5 },
    { id: 3, name: 'Петя', value: 6 }
]
```
Делаем новый массив через find и получаем массив ссылок на объекты (не объекты): 
```js
const array = arr.map(({id}) => arr.find(a => a.id === id));
console.log(array); /*
[
    { id: 1, name: 'Вася', value: 1 },
    { id: 2, name: 'Петя', value: 2 },
    { id: 1, name: 'Вася', value: 1 },
    { id: 1, name: 'Вася', value: 1 },
    { id: 2, name: 'Петя', value: 2 },
    { id: 3, name: 'Петя', value: 6 }
]
*/
```

Далее уже `new Set`
```js
console.log(new Set(array));
/*
Set {
  0: { id: 1, name: 'Вася', value: 1 },
  1: { id: 2, name: 'Петя', value: 2 },
  2: { id: 3, name: 'Петя', value: 6 }
}
*/

2024-12-09 19:10 UTC, mikhail-os-git commented
Но как это возможно, не понимаю, получается уникализация происходит вот здесь "const array = arr.map(({id}) => arr.find(a => a.id === id));" а не благодаря Set? Вот здесь мы сверяем, получается, значения и в зависимости от true или false, используем одну и ту жу ссылку или нет, после чего уже удаляем в Set одинаковые ссылки? Если я правильно понял из лекции Set не уникализирует ссылочные типы. Значит при создании промежуточного массива, происходит сравнение и передача ссылки при одинаковых значениях а уже после удаление их в Set?

2024-12-10 09:24 UTC, GitEsense requested changes
Таймер поправить бы, в остальном оставил примеры

2024-12-10 09:24 UTC, GitEsense commented on 6-class/app.js
> +audi.info();
оставлю в качестве примера
```js
class Car {
    #_brand;
    #_model;
    #_mileage;

    constructor(brand, model, mileage) {
        this.#_brand = brand;
        this.#_model = model;
        this.#_mileage = mileage;
    }

    get mileage() {
        return this.#_mileage;
    }

    set mileage(value) {
            if (!this.#checkMileage(value)) {
                console.error(
                    `the values ​​are the same(current: ${this.mileage}, new: ${value}).Mileage NOT changed`
                );
                return false;
            }

            console.log(`mileage changed from ${this.mileage} to ${value} `);
            this.#_mileage = value;
            return true;
    }

    #checkMileage(value) {
        return this.#_mileage >= value;
    }

    info() {
        console.log(
            `Марка: ${this.#_brand}, Модель: ${this.#_model}, Пробег: ${this.mileage}`
        );
    }
}

const car1 = new Car("Audi", "A6", 10000);
car1.mileage = 10001
car1.mileage = 2500
car1.info();

const car2 = new Car("BMW", "X5", 1500);
car2.mileage = 5000;
car2.mileage = 5000;
car2.info();
```

2024-12-10 09:24 UTC, GitEsense commented on 5-oop/app.js
> +rogmorrok.incantation();
Всё отлично, оставлю такую реализацию, практически схожа с Вашей, но добавлены "проверки", для видимости "отличий"
```js
'use strict';

const Character = function (race, name, language) {
    this.race = race;
    this.name = name;
    this.language = language;
};

Character.prototype.talk = function () {
    console.log(`Язык: ${this.language}, Имя: ${this.name}`);
};

const Ork = function (race, name, language, weapon) {
    Character.call(this, race, name, language);
    this.weapon = weapon;
};

Ork.prototype = Object.create(Character.prototype);
Ork.prototype.constructor = Ork;
Ork.prototype.blow = function () {
    console.log(`${this.race} по имени ${this.name} использует своё оружие ('${this.weapon}') и наносит удар!`);
};

const Elf = function (race, name, language, spell) {
    Character.call(this, race, name, language);
    this.spell = spell;
};

Elf.prototype = Object.create(Character.prototype);
Elf.prototype.constructor = Elf;
Elf.prototype.createSpell = function () {
    console.log(`${this.race} по имени ${this.name} использует своё заклинание ('${this.spell}') и наносит удар!`);
};

const ork = new Ork('Орк', "Гул'дан", 'Орочий', 'Топор');
const elf = new Elf('Эльф', 'Sulmeldis', 'Эльфийский', 'Взрыв');
ork.talk();
ork.blow();

elf.talk();
elf.createSpell();

console.log('ork instanceof Character:', ork instanceof Character);
console.log('ork instanceof Ork:', ork instanceof Ork);
console.log('ork instanceof Elf:', ork instanceof Elf);

console.log('elf instanceof Character:', elf instanceof Character);
console.log('elf instanceof Ork:', elf instanceof Ork);
console.log('elf instanceof Elf:', elf instanceof Elf);

2024-12-10 09:24 UTC, GitEsense commented on 4-timer/scripts/app.js
> +// }
Почитайте о библиотеке `Intl.DateTimeFormat`, ну и в целом про `Intl`

2024-12-10 09:24 UTC, GitEsense commented on 4-timer/scripts/app.js
> +timeLeft();
Хорошо бы в интервал вложить вызов с передачей `diff` в миллисекундах, чтобы уже конвертировать (вычислять), так же формулы немного надо будет подправить

Не плохо было бы при "старте" программы вычислить "сегодня", вычислить разницу до НГ и передать в функцию для старта, далее в интервале передавать `diff` со снижением значения, например
```js
let diff = new Date(`${new Date().getFullYear() + 1}-01-01T00:00:00`) - Date.now();
        const interval = setInterval(() => {
           / * Тут логика остановки, если НГ уже наступил */
            renderTimer(diff -= 1000) // Функция рендера времени в HTML
        }, 1000);

2024-12-16 09:29 UTC, GitEsense approved these changes

2024-12-16 09:29 UTC, GitEsense commented on 4-timer/scripts/app.js
> -timeLeft();
В целом всё отлично, только можно было бы сделать функцию "шаблона" сообщений на вывод и предусмотреть остановку таймера, если НГ наступил (остановить таймер)

Оставлю Вам один из вариантов реализации, а там посмотрите "на вкус и цвет"

```js
window.addEventListener('load', () => {
    const page = {
        time: {
            'months': "",
            'days': "",
            'hours': "",
            'minutes': "",
            'seconds': "",
        },
        'wrapper': document.querySelector('.timer__wrapper'),
    }

    function getTimeForDate(ms) {
        const second = Math.floor(ms / 1000);
        const minute = Math.floor(second / 60);
        const hour = Math.floor(minute / 60);
        const day = Math.floor(hour / 24);
        const month = Math.floor(day / 30.425);

        return {
            'months': month % 12,
            'days': Math.floor(day % 30.425),
            'hours': hour % 24,
            'minutes': minute % 60,
            'seconds': second % 60,
        }
    }
    function createLabel(num, key) {
        const labels = {
            months: { one: 'месяц', few: 'месяца', many: 'месяцев' },
            days: { one: 'день', few: 'дня', many: 'дней' },
            hours: { one: 'час', few: 'часа', many: 'часов' },
            minutes: { one: 'минута', few: 'минуты', many: 'минут' },
            seconds: { one: 'секунда', few: 'секунды', many: 'секунд' },
        }

        const plural = new Intl.PluralRules('ru-RU', { type: 'cardinal' }).select(num);
        return labels[key][plural]
    }

    function renderTimer(time) {
        const data = getTimeForDate(time)
        Object.entries(data).map(([key, value]) => {
            const text = createLabel(value, key);
            const count = data[key].toString().padStart(2, '0');
            page.time[key].text.innerHTML = text;
            page.time[key].value.innerHTML = count;
        })
    }

    function templateMessage(text) {
        return `<div style="color: red; font-weight: 700; font-size: 32px; text-align: center;">${text}</div>`
    }

    function createTimerContainer() {
        const timer = document.createElement('div');
        timer.classList.add('timer');

        const title = document.createElement('h2');
        title.classList.add('timer__title');
        title.innerHTML = "До <span>нового года</span> осталось:"
        Object.keys(page.time).forEach(key => {
            const div = document.createElement('div');
            div.classList.add(`timer__column`, `timer__${key}`);

            const value = document.createElement('div');
            value.classList.add(`timer__${key}`, `timer__count`)

            const text = document.createElement('div');
            text.classList.add(`timer__${key}`, `timer__description`);
            div.append(value, text)
            page.wrapper.append(div)
            page.time[key] = {
                value,
                text
            }
            timer.append(div)
        })
        page.wrapper.append(timer);
    }

    let diff = new Date(`${new Date().getFullYear() + 1}-01-01T00:00:00`) - Date.now();
    createTimerContainer();
    if (diff < 0) {
        console.log(page.wrapper.setAttribute('style', 'flex-direction: column;'));
        page.wrapper.innerHTML = templateMessage('Ошибка')
        page.wrapper.innerHTML += templateMessage('Укажите дату и время позднее текущего')
    } else {

        const interval = setInterval(() => {
            if (Math.floor(diff / 1000) === 0) {
                page.wrapper.innerHTML = templateMessage('Happy New Year!')
                clearInterval(interval);
                return
            }
            renderTimer(diff -= 1000)
        }, 1000);
    }
})
```

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="styles.css">
    <title>Happy New Year - Timer</title>
    <script src="./script.js"></script>
</head>

<body>
    <div class="timer__wrapper">

    </div>
</body>

</html>
```

```css
html,
body,
.timer__wrapper {
    height: 100%;
}

body {
    font-size: 14px;
    font-family: 'Roboto', sans-serif;
    margin: 0;
}

.timer__wrapper {
    display: flex;
    justify-content: center;
    align-items: center;
}

.timer {
    /* width: 100%;
    max-width: 480px; */
    min-height: 148px;
    background: #d4dbe8;
    padding: 26px;
    border-radius: 20px;
    box-shadow: 6px 6px 4px 0px rgba(10, 37, 64, 0.5);
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 20px;
}

.timer__title {
    padding: 0;
    margin: 0;
    margin-bottom: 15px;
    font-size: 1rem;
    text-transform: uppercase;
    font-weight: 900;
    color: #0a2540;
}

.timer__title span {
    color: #0070f0;
}

.timer__container {
    display: grid;
    grid-template-columns: 1fr 1fr 1fr 1fr 1fr;
    gap: 10px;
}

.timer__column {
    width: 80px;
    min-height: 96px;
    background: #f2f5f9;
    padding: 14px;
    border-radius: 10px;
}

.timer__count {
    display: flex;
    justify-content: center;
    align-items: center;
    background: #f2f5f9;
    color: #0a2540;
    display: grid;
    font-weight: 800;
    font-size: 2.8rem;
}

.timer__seconds>.timer__count {
    color: rgb(248, 26, 118);
}

.timer__description {

    text-align: center;
    font-size: 0.7rem;
    font-weight: 600;
    color: #0070f0;
}
```

2024-12-16 09:57 UTC, merged